### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by jo-elimu** [marytts/marytts-txt2wav#5]
Hi,

How do I change to one of the other languages included in MaryTTS? For example, how do I change from the default voice to a German voice?

If I try with marytts-**lang-de** in 

```
   <dependency>
      <groupId>de.dfki.mary</groupId>
      <artifactId>marytts-lang-de</artifactId>
      <version>5.2-beta3</version>
   </dependency>
```

and 
`mary.setLocale(new Locale("de"));`, 
I get 
`Exception in thread "main" java.lang.IllegalArgumentException: No voice is available for Locale: de`

Any suggestions?

**Comment by psibre** [comment]
If you add `marytts-lang-de`, you add the capability to process up to `ALLOPHONES`, but for any output type beyond that, such as `AUDIO`, you'll need to have an actual voice dependency, e.g.,

``` xml
<dependency>
   <groupId>de.dfki.mary</groupId>
   <artifactId>voice-bits3-hsmm</artifactId>
   <version>5.1.2</version>
</dependency>
```

The catch is that those voices are not _officially_ available in any binary repository yet, so you'll need to either
1. obtain it somehow (such as by installing it with the `marytts-component-installer`), _or_ 
2. configure http://mary.dfki.de/repo/ as an additional repository,
and then make sure that your maven can resolve the dependency.
You'll also want to override the transitive dependency version, to take advantage of the improvements since v5.1.2.
All of this is fairly straightforward with gradle, but could also be done with ant (via ivy) or maven.

**Comment by jo-elimu** [comment]
Thank you for the help, @psibre :-)

**Comment by psibre** [comment]
HTH! =)
